name: Docker Build

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate Dockerfile
      run: |
        if [ ! -f Dockerfile ]; then
          echo " Dockerfile no encontrado"
          exit 1
        fi
        cat Dockerfile  # Muestra el contenido para debug

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker buildx build --platform linux/amd64 -t pokemon-api:latest . --load